name: github pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    timeout-minutes: 2
    runs-on: macos-latest # ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout yuripages
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          repository: Yrr0r/yuripages
          path: themes/yuripages

      - name: Patch html
        run: |
          mkdir -p layouts/section
          cp themes/yuripages/layouts/index.html layouts/section/blocklist.html.html
          cp content/index.html layouts/index.html

      - name: Reset mtime
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'
      - run: python3 git_reset_mtime.py

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'

      - name: Build 4
        run: hugo --minify --debug --path-warnings --verboseLog

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./public
