name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout amaki-aria.github.io
        uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Checkout yuripages
        uses: actions/checkout@v2
        with:
          repository: Yrr0r/yuripages
          path: themes/yuripages

      - name: Patch html
        run: |
          mkdir -p layouts/section
          cp themes/yuripages/layouts/index.html layouts/section/blocklist.html.html
          cp content/index.html layouts/index.html

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.80.0'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
